# ----------------------------
# Application
# ----------------------------
spring.application.name=BankingSystem
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
# ----------------------------
# Datasource (H2 In-Memory)
# ----------------------------
spring.datasource.url=jdbc:h2:mem:bankingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ----------------------------
# JPA / Hibernate
# ----------------------------

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ----------------------------
# Flyway Database Migration
# ----------------------------


# ----------------------------
# H2 Console
# ----------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=vfdwVkq0kJ7mQMy_5qLpeaBV2VdhLbxNm5zbizeMJMtt-ZK-IGHp75J60_ReUZyAN0BTK-8gLrXCyiIrkCSqKA
jwt.expirationMs=3600000
jwt.refreshExpirationMs=604800000


